Added check for root, added drush path, took out some echos

diff --git a/provisioning/drupal8-util b/provisioning/drupal8-util
--- a/provisioning/drupal8-util
+++ b/provisioning/drupal8-util
@@ -9,6 +9,12 @@
 # Include the helper functions
 . functions.sh
 
+# Make sure only root can execute the script
+if [[ ${EUID} != 0 ]]; then
+  echo -e "${RED}You are required to run this script as root or with sudo! Aborting...${COLOR_ENDING}"
+  exit 1
+fi
+
 #eventually ./drupal-util reinstall path/to/docroot
 usage() {
   send_message 'Usage: ./reinstall install|reinstall|delete|help /path/to/docroot [database name]'
@@ -25,6 +31,7 @@ case "$1" in
         setup
         files_create
         database_create
+        drupal_install
         ;;
   reinstall)
         setup
@@ -32,6 +39,7 @@ case "$1" in
         files_create
         database_delete
         database_create
+        drupal_install
         ;;
   delete)
         setup
